version: '3.7'

services:
  web:
    build: .
    container_name: qdrant_demo_web
    ports:
      - 8000:8000
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - qdrant-net
  qdrant:
    image: generall/qdrant:latest
    mem_limit: 600m
#    ports:
#    - 6333:6333
    volumes:
      - ./data/qdarnt_storage:/qdrant/storage

    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
