[tool.poetry]
name = "qdrant_demo"
version = "0.1.0"
description = "Qdrant vector similarity engine demo"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]

[tool.poetry.dependencies]
python = "~3.8"
tensorflow-hub = "^0.10.0"
fastapi = "^0.61.2"
uvicorn = "^0.12.3"
#openapi-client = {path = "qdrant_client"}
qdrant-api-client = {path = "qdrant-api-client"}
sentence-transformers = "^0.3.9"
psutil = "^5.7.3"
nltk = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
